# === VOICE MAP ===
VOICE_MAP = {
    "en-US": "en-US-natalie",
    "en-UK": "en-UK-theo",
    "en-IN": "en-IN-aarav",
    "en-AU": "en-AU-jimm",
    "en-SCOTT": "en-SCOTT-rory",
    "es-MX": "es-MX-carlos",
    "es-ES": "es-ES-carla",
    "fr-FR": "fr-FR-axel",
    "de-DE": "de-DE-matthias",
    "it-IT": "it-IT-lorenzo",
    "nl-NL": "nl-NL-merel",
    "pt-BR": "pt-BR-heitor",
    "zh-CN": "zh-CN-tao",
    "ja-JP": "ja-JP-denki",
    "ko-KR": "ko-KR-hwan",
    "hi-IN": "hi-IN-kabir",
    "ta-IN": "ta-IN-mani",
    "bn-IN": "bn-IN-ishani",
    "sk-SK": "sk-SK-tibor",
    "pl-PL": "pl-PL-jacek",
    "el-GR": "el-GR-stavros",
    "hr-HR": "hr-HR-marija",
}

# Language map
MURF_LANGUAGES = {
    "en-US": "English - US & Canada",
    "en-UK": "English - UK",
    "en-IN": "English - India",
    "en-AU": "English - Australia",
    "en-SCOTT": "English - Scotland",
    "es-MX": "Spanish - Mexico",
    "es-ES": "Spanish - Spain",
    "fr-FR": "French - France",
    "de-DE": "German - Germany",
    "it-IT": "Italian - Italy",
    "nl-NL": "Dutch - Netherlands",
    "pt-BR": "Portuguese - Brazil",
    "zh-CN": "Chinese - China",
    "ja-JP": "Japanese - Japan",
    "ko-KR": "Korean - Korea",
    "hi-IN": "Hindi - India",
    "ta-IN": "Tamil - India",
    "bn-IN": "Bengali - India",
    "hr-HR": "Croatian - Croatia",
    "sk-SK": "Slovak - Slovakia",
    "pl-PL": "Polish - Poland",
    "el-GR": "Greek - Greece"
}

WHISPER_MAP = {
    "en-US": "en",
    "en-UK": "en",
    "en-IN": "en",
    "en-AU": "en",
    "en-SCOTT": "en",
    "es-MX": "es",
    "es-ES": "es",
    "fr-FR": "fr",
    "de-DE": "de",
    "it-IT": "it",
    "nl-NL": "nl",
    "pt-BR": "pt",
    "zh-CN": "zh",
    "ja-JP": "ja",
    "ko-KR": "ko",
    "hi-IN": "hi",
    "ta-IN": "ta",
    "bn-IN": "bn",#verify if bengali is supported by Whisper
    "sk-SK": "sk",
    "pl-PL": "pl",
    "el-GR": "el",
    "hr-HR": "hr",
}